:doctype: book
:imagesdir: images
:stylesheet: paper.css
// Disable generating an update label at the bottom of the doc.
:last-update-label!:
// Setup highlight.js to use a local version with a local stylesheet
:source-highlighter: highlight.js
:highlightjs-theme: thesis
:highlightjsdir: libraries/highlightjs
// Enable rendering math equations
:stem:
// Generate a table of contents at the toc macro
// Also disabling section numbers for now, as we only start numbering after the toc. See the macros there
:toc: macro
:toclevels: 3
:sectanchors:
// Disable the title page
// We will build the title page manually for maximum flexibility
:notitle:
:title-page: false
// Refer to things like "Figure 1" instead of by their name
:xrefstyle: short
// Prefetch and inline diagrams with kroki but not in vscode
ifndef::env-vscode[]
:kroki-fetch-diagram: true
:kroki-default-options: inline
endif::env-vscode[]

image::../assets/logo_hda.svg[role=logo]

[.university.text-center]
Darmstadt University of Applied Sciences

[.faculty.text-center]
Faculty of Computer Science

[discrete#main-title]
= cryptography lab report 2

[.presented-by.text-center]
by +
*Lennart Eichhorn* +
[small]+Matriculation number: 759253+ +


// Start with section and part numbering
:part-signifier: Part
:sectnums:
:listing-caption: Listing
:partnums:

// Main part starts here
[.reset-pages]
= Report

== Introduction

=== Simple AES programming

The supplied simple AES implementation shown <<reference-simple-aes>> was supplied as a reference. However it is missing the inverse S-Box required for decryption. Our first task is to implement the inverse S-Box and then use it to implement the decryption function.

We wanted to have a known working encryption and decryption implementation to compare our implementation against. For this we build simple implementation using the openssl library, as shown in <<reference-openssl-aes>>. We then verified that the openssl implementation produces the same output as the simple implementation.

<<inverting-the-sbox>> shows our function for calculation the inverted SBOX table. It swaps the indices and values of the SBOX table, to create the inverted table. We added the inverted SBOX into the simple AES implementation. We confirmed that the decryption function now works correctly by fuzzing the implementation against 1000000 random blocks and keys. As shown in <<fuzzing-decryption>>, we validated the result for each block by comparing it with the openssl implementation.

.`openssl` based AES tool
[source#inverting-the-sbox.linenums,cpp]
----
include::src/invert-sbox.cpp[tag=invert-sbox]
----

.Setup for comparing our implementation against openssl
[source#fuzzing-decryption.linenums,cpp]
----
include::src/simple-aes.cpp[tag=main]
----

== Simple AES cracking

For the second exercise we were tasked with recovering a partially lost 128-bit (16-byte) AES key (shown in <<partially-known-key>>). We were supplied with the first 13 bytes of the key and a ciphertext that is known to decrypt to only ASCII characters matching the regex `[a-z.]`. The partial key and the ciphertext are shown in <<recovery-supplied-data>>.

.Supplied data for the second exercise
[source#recovery-supplied-data.linenums,cpp]
----
include::src/key-recovery.cpp[tag=supplied-data]
----

// We only know the first 13 bytes of the key, so we need to bruteforce the remaining 3 bytes.

== Appendix

.Simple reference AES implementation
[source#reference-simple-aes.linenums,cpp]
----
include::src/simple-aes.cpp[]
----

.`openssl` based AES tool
[source#reference-openssl-aes.linenums,cpp]
----
include::src/openssl-aes.cpp[]
----

include::scripts/trailing-scripts.adoc[]

// Final checklist:
// * are all abbreviations defined?
// * are all abbreviations linked to Wikipedia (or somewhere else)?
// * are all references used?
// * are all references linked to the correct source?
// * are all TODOs processed?
// * are the names for things consistent?
// * check for broken references
// * archive.org all links
// * Check for duplication of information
// * oxford comma
// * You should have read the paper at least once from top to bottom.